name: Lint Check
on:
  pull_request:
  push:
    branches: main
    paths:
      - 'lxc/*.py'
      - '.github/workflows/check.yml'
      - 'kernelsu/*.py'
      - 'rekernel/*.py'
      - 'nethunter/*.py'

jobs:

  sh-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        lint: [mypy, pyline]

    steps:
      - uses: actions/checkout@v6
      - name: lint
        if: matrix.lint == 'mypy'
        run: |
          sudo apt install mypy -y
          mypy --explicit-package-bases $(find | grep .py)

      - name: lint
        if: matrix.lint == 'pylint'
        run: |
          sudo apt install pylint -y
          rm mkdtboimg.py
          pylint $(find | grep .py)
